import { chromium } from 'playwright';
const BASE = 'http://localhost:8080';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1360, height: 1200 }, locale: 'en' });
const page = await ctx.newPage();
await page.goto(BASE + '?seed');
await sleep(1500);
await page.click('.cup-card:not([disabled]):last-child');
await sleep(800);
await page.click('.team-card:first-child');
await page.waitForSelector('.pcard.pc-mini', { timeout: 6000 });
await sleep(800);
await page.screenshot({ path: 'pwtest-shots/05-roster-mini.png' });
await page.click('.btn.big.primary');
await sleep(2000);
await page.click('.cmd-bar .btn.primary.big');
await page.waitForSelector('.pc-pick', { timeout: 8000 });
await page.locator('.pc-pick').nth(1).click();
await sleep(300);
await page.screenshot({ path: 'pwtest-shots/06-lineup-armed.png' });
await page.locator('.slot-marker:not(.filled)').first().click();
await sleep(400);
await page.click('.btn.secondary.big');
await sleep(300);
await page.click('.bar-hint .btn.big.primary');
await sleep(1800);
await page.waitForSelector('.score-row', { timeout: 8000 });
await page.locator('.score-row:has(.focus-tag)').last().click();
await page.waitForSelector('.momentum', { timeout: 8000 });
await sleep(4200);
await page.screenshot({ path: 'pwtest-shots/07-match-chart.png', clip: { x: 232, y: 340, width: 900, height: 520 } });
await page.waitForSelector('.match-actions', { timeout: 25000 });
await page.screenshot({ path: 'pwtest-shots/08-match-end.png' });
await browser.close();